apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: timoni-build
spec:
  init:
    command: []
    args: []
  generate:
    command: ["/bin/sh", "-c"]
    args:
      - |
        # Extract branch name from target revision
        BRANCH=$(echo "$ARGOCD_APP_SOURCE_TARGET_REVISION" | sed 's|refs/heads/||')
        /usr/local/bin/timoni build timoni-build . -f values-${BRANCH}.cue -f image-${BRANCH}.cue
  discover:
    filename: "timoni.cue"
