apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: timoni-build
spec:
  init:
    command: []
    args: []
  generate:
    command: ["/bin/sh", "-c"]
    args:
      - |
        /usr/local/bin/timoni build timoni-build . -f values-${ARGOCD_ENV_Environment}.cue -f image.cue
  discover:
    filename: "timoni.cue"
